import './styles/globals.css';
import '@/components/firebase/config';
import AuthProvider from '@/components/common/AuthProvider';
import ProtectedRoute from '@/components/common/ProtectedRoute';

export const metadata = {
    title: 'Notes',
    description: 'Generated by create next app',
    keywords: 'nextjs, react, firebase',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <AuthProvider>
                    <ProtectedRoute>{children}</ProtectedRoute>
                </AuthProvider>
            </body>
        </html>
    );
}
